developer/installation.md
Because it doesn't always work
=> Remove references to `reaction install`

admin/dashboard.md, admin/faq.md, admin/products.md, admin/tags.md, developer/architecture/layout.md, developer/deploying/heroku.md
Just stuff I found when trying to read the whole doc from end-to-end.
=> Fix images and links.

developer/architecture/i18n.md, developer/core/import.md, developer/deploying.md, developer/testing/velocity.md, developer/themes/templates.md
Fixes as but the link to Ongoworks. Closes #30
=> Fixes for some random broken links

developer/packages/including.md, redoc.json
=> Change references from "cycle" to priority

developer/architecture/collections.md
Updated collection docs to reflect changes made in https://github.com/reactioncommerce/reaction/pull/971
=> Updated Collections docs

developer/architecture/layout.md, developer/architecture/routing.md
for https://github.com/reactioncommerce/reaction/pull/985
=> Layout Options

developer/installation.md, index.md
=> updated installation.md

developer/configuration.md
remove MONGO_URL ref from settings.
=> updated configuration.md

developer/requirements.md
cleanup and add Ubuntu to requirements documentation for #63
=> updated requirements.md

guidelines/changes.md, guidelines/code-of-conduct-committee.md, guidelines/code-of-conduct.md, guidelines/diversity-statement.md, guidelines/enforcement.md, guidelines/faqs.md, guidelines/guidelines.md, guidelines/reporting-guide.md, redoc.json
Resolves https://github.com/reactioncommerce/reaction/issues/894
Initial release of Reaction’s community guidelines
=> Reaction Community Guidelines

developer/architecture/routing.md
Updates for `Router.Hooks` API and a few general cleanups
=> add docs for hooks and cleanup some general router stuff

developer/core/payments.md, developer/packages/payments/authnet.md, developer/packages/payments/braintree.md, developer/packages/payments/paypal.md, developer/packages/payments/stripe.md, redoc.json
Adding docs for each individual payment provider, detailing the process each goes through when Authorizing, Capturing, Refunding, and discounting.
=> Docs for individual payment providers

developer/packages/payments/braintree.md, developer/packages/payments/paypal.md
Fixed a couple typos in the new payments docs
=> fixed a few typos

developer/architecture/security.md
- related to https://github.com/reactioncommerce/reaction/issues/1330
- Cleanup and clarify browser-policies implementation.
- Get rid of some of the excess quoting -> this page is just an
overview, and might be redundant.
=> updated security.md

developer/packages/search.md, redoc.json
A simple explanation of Search and how it works.
=> Add Search plugin documentation

developer/module-cheatsheet.md, redoc.json
Added a cheatsheet doc for some of the most common imports I could find throughout the app.
=> Added module import cheatsheet

developer/architecture/collections.md, developer/architecture/metadata.md, developer/components/upload.md, developer/core/collection-hooks.md, developer/core/hooks.md, developer/core/shops.md, developer/themes/templates.md, developer/tutorial/creating-a-plugin.md, package.json, redoc.json
- fix ReactionRouter references
- fix ReactionCore references
- update npm deps for linters
- fix class name typo in side nav links
- fix link to email doc
=> Quick fixes

developer/themes/templates.md
See: 
https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/product-variant/client/templates/products/products.html
:)
=> New plugin templates path

developer/styleguide.md
https://github.com/reactioncommerce/reaction/issues/1416
=> File naming conventions

developer/core/products.md
=> `createVariant` code example fix.

developer/architecture/logging.md
Updates to go along with https://github.com/reactioncommerce/reaction/pull/1574
=> update logger docs

developer/core/event-hooks.md
=> Add documentation for Event hooks

admin/faq.md
=> Remove broken link to Meteorpedia

developer/deploying/heroku.md
Resolves #101 
Doing the tough work
=> Fix Heroku buildpack link

developer/architecture/prerender.md, redoc.json
Docs for Prerender.io integration [reaction#1643](https://github.com/reactioncommerce/reaction/pull/1643)
=> Documentation for Prerender.io integration

developer/components/multi-select.md, developer/components/slider.md, developer/core/admin.md, developer/tutorial/creating-a-theme.md, redoc.json
Added admin view docs for both the publish bar (top toolbar) and action view (side bar) for developers.
=> Admin view docs

developer/deploying/docker.md
- Update a few outdated links
- Remove references to deprecated Docker Toolbox
- update default exposed port to 3000
- simplify steps (less is more)
=> update/simplify Docker deployment docs

developer/components/multi-select.md, developer/components/slider.md, developer/core/admin.md, developer/core/event-hooks.md, developer/deploying/docker.md, developer/docker-demo.md, developer/installation.md, redoc.json
=> Merge dev docs to master

developer/architecture/permissions.md
To be consistent with his fellow methods above.
=> `hasPermission` export path 

admin/faq.md, developer/architecture/jobcontrol.md, developer/core/import.md, developer/packages/search.md, developer/testing/factories.md, developer/tutorial/creating-a-payment-provider-plugin.md, developer/tutorial/introduction.md, developer/tutorial/plugin-fixtures-5.md, developer/tutorial/plugin-i18n-9.md, developer/tutorial/plugin-intro-1.md, developer/tutorial/plugin-layouts-3.md, developer/tutorial/plugin-routes-6.md, developer/tutorial/plugin-schemas-8.md, developer/tutorial/plugin-workflow-7.md, developer/tutorial/testing-tutorial.md
I've been reading through the docs and fixed some typos as part of the process.
I've also replaced ecommerce with eCommerce as both where used across the docs.
=> Fixing Typos and improving consistency

redoc.json
can be merged to master after merged to dev
=> Add settings card doc to TOC

developer/requirements.md
I searched for ENFILE to try to help out in the Gitter chat, no results... hopefully this will help out with search.
=> updated EMFILE to ENFILE

developer/deploying/launchdock.md
This updates and extends the managed platform docs.
=> update managed platform docs

developer/testing/react_testing.md
**Description**
How to test components and what to test.
=> Testing React Components

admin/orders.md
=> fix broken screenshot

admin/dashboard.md
=> update old screenshot

developer/tutorial/introduction.md, developer/tutorial/plugin-complete-10.md, developer/tutorial/plugin-creating-2.md, developer/tutorial/plugin-customizing-templates-4.md, developer/tutorial/plugin-fixtures-5.md, developer/tutorial/plugin-i18n-9.md, developer/tutorial/plugin-intro-1.md, developer/tutorial/plugin-layouts-3.md, developer/tutorial/plugin-routes-6.md, developer/tutorial/plugin-schemas-8.md, developer/tutorial/plugin-workflow-7.md
- Fixes more URL bugs in the theming and tutorials sections
- Test here: https://docs.reactioncommerce.com/reaction-docs/add-md-suffix-to-hyperlinks/tutorial
=> fix hyperlinks

README.md
Adds testing section to README.md
=> Add flush doc command

developer/community.md, developer/testing/ci.md
- add Gcal link to community mtgs
- fix links
- avoid `etc.`
=> Edit community.md

developer/components/API.md, developer/components/README.md, redoc.json
=> WIP - document new React components API

developer/community.md
* combine Theme/Appearance with Customization Guide in TOC (#242)
* Admin Guide (#228)
* 1. adds dashboard/admin files for all dashboard panels, 2. adds /dashboard/ directory for all dashboard how tos, 3. reorganizes Introduction into Store Operator section, 4. edits text for copy/url fixes, etc.
* remove unused images. saved locally for archiving purposes.
* Accounts section is ready.
* Login section is ready.
* update account imgs and text
* social
* catalog pg
* icons and ss
* product pg
* Update products.md
* Update orders-admin.md
* adds shippo. icons.
* removes rates
* add last icon
* fix login services
* add tax
* Updated remark cli (#247)
* Updated remark-lint
* Docs updated with remark-lint
* Update remark config to v6 style (#248)
* update remarkrc configuration to remark v6 …
=> Merge development into master (#259)

developer/components/sortableTable.md, redoc.json
Docs for the SortableTable component
=> sortableTable docs

developer/testing/vulnerabilities.md, redoc.json
Add security reporting instructions. (Send to email group). Adds to testing nav.
=> Add vulnerability reporting instructions

developer/deploying/docker.md
I made the other one unclean as it was from marketplace, and was conflicting in places and got messy, here is a clean PR, ignore #269
=> Added custom build section

developer/deploying/docker.md
fix link to installation docs in the [docker deployment guide](https://docs.reactioncommerce.com/reaction-docs/master/deploying-reaction-using-docker)
=> fix broken link

developer/configuration.md
https://github.com/reactioncommerce/reaction/pull/2627
=> Add Skip Fixtures variable

developer/requirements.md
Added instructions on how to set file limits in macOS following the discussion on the stack overflow link already given.
=> Update setting file limits in macOS

developer/architecture/schemas.md
Documentation for the new registerSchema() method.
=> registerSchema documentation

developer/tutorial/plugin-creating-2.md
Need to add: git submodule instructions, screenshot of terminal
- Number steps and sub-steps
- Add all command line instructions
- Add links to relevant blog posts, files in example plugin
=> Update step 2

developer/components/avatar.md, redoc.json
Docs for using the ReactionAvatar component.
=> Docs for ReactionAvatar component

developer/architecture/collections.md, developer/architecture/prerender.md, developer/architecture/schemas.md, developer/core/cart.md, developer/installation.md, developer/themes/helpers.md, developer/themes/themes.md, developer/tutorial/plugin-layouts-3.md, index.md
Remove `development` breaking urls from `master` docs.
=> Remove all development branch anchor use

developer/styleguide.md
+ lint
test: https://docs.reactioncommerce.com/reaction-docs/copy-style/styleguide#copy-conventions
- rendered:
=> style guide: add rules for sentence casing

developer/architecture/permissions.md
Update docs for Custom Default Groups (ref https://github.com/reactioncommerce/reaction/pull/3117)
=> Update docs for Custom Default Groups

developer/components/API.md
Someone forgot to resolve an old conflict.
=> Update API.md: Typo (Kill conflict merge issue)

admin/dashboard.md
Update to some confusing text noticed when browsing the docs.
=> add missing text and link

developer/architecture/permissions.md
Resolves #299 
Add comment about change in defaultRoles list from pre v.1.50
=> Add comment about defaultVisitorRoles

admin/faq.md
Update FAQ for easier navigation to Reaction Platform page
=> Add Reaction Platform URL to Inline Text

admin/faq.md
Added a grammar correction related to linking Reaction Platform
=> Added Grammatical Correction

developer/core/product-detail.md
Components module import and usage was deprecated.
=> Updates Component API Documentation to 1.5.4

developer/community.md
We're changing the community call time from 7AM PST to 9AM PST b/c several community members in S. America time zones have requested it. Looking forward to seeing them at the call.
=> Update community call time to 9AM PST

developer/developer-faqs.md, redoc.json
A placeholder for capturing answers to developers FAQ from Gitter, Forums, etc.
=> Add Developer FAQ

developer/tutorial/plugin-layouts-3.md
Switching `/client/templates/layoutes/core.js` to `/client/templates/layouts/core.js`. I believe this is a typo.
=> Typo in Path

developer/developer-faqs.md
=> Answer SEO question

developer/developer-faqs.md
Closes #343 
@machikoyasuda How we want to format these so they are linkable and easier to see the questions? I played around a little bit but couldn't come up with anything that worked great.
=> Answer admin panel questions

admin/faq.md, developer/data-fixtures-insert-product-images.md
This PR fixes the issue #354.
FAQs: How can I upload product images as part of a data fixture?
=> Fix for issue #354.

redoc.json
Adds Code Review to TOC https://docs.reactioncommerce.com/reaction-docs/machikoyasuda-code-review-toc/code-reviews
=> Add Code Review to Table of Contents

admin/faq.md, developer/data-fixtures-insert-product-images.md
This PR is a fix for the old PR , that missed some example code.
It affects this issue: #354
=> Amendment to issue 354: missing code

admin/faq.md
I want to make a change to the schema and use it in the PDP
=> Resolves issue #339:

developer/requirements.md
=> Addendum to the instruction on how to increase osx file limits.

admin/faq.md, admin/tagging.md
Obviously there are slight differences between different markdown editors..
=> Fix formatting for tagging introduction

admin/faq.md
I want to use XYZ payment provider/Shipper how do I do that?
=> This PR resolves issue 341.

developer/tutorial/plugin-routes-6.md
addresses issue from https://github.com/reactioncommerce/reaction-docs/pull/366
=> docs: add link to Routing architecture doc

developer/tutorial/creating-a-payment-provider-plugin.md
=> Fix wrong paths in payment provider tutorial.

developer/community-resources.md, developer/developer-faqs.md, redoc.json
=> New page `Add community plugins/packages/themes/recommendations list`

redoc.json
=> table of contents: add Testing tutorial to TOC

developer/requirements.md
=> Set install back to "latest" and add instructions for Windows

developer/community-resources.md, redoc.json
this PR Resolves #399.
Also the headings are change to h3, because h4 is not different from normal type face.
=> Fix for double navigation entry. change h4 to h3

developer/deploying/docker.md
Looks like it's not liking relative URLs, not sure though..
=> Link to page 'customization guide' is not working.

developer/themes/templates.md, redoc.json
=>  Deprecation notice for page "Extending blaze templates"

developer/installation/installation-linux.md
Running that command to fix permissions (that is from the NodeJs site) may cause some problems so I am removing it for now until I can test some more
=> Remove package installer instructions

developer/developer-faqs.md
=> Add questions about performance

developer/developer-faqs.md
=> Add notes about hosting platforms

index.md
=> Fix: Content blocks on Docs are different sizes

developer/developer-faqs.md
Closes #352 
This is the 411 😆  -- #old
=> Talk about static pages and CMS integration

developer/architecture/schemas.md
=> Fix wrong path on page schemas.md

developer/community-resources.md
Add our first community plugin to curated list of resources for Reaction
=> Add payments-cod plugin to list of available Reaction plugins.

developer/components/csvDownload.md, redoc.json
Docs for the new CSVDownload component.
PR for component: https://github.com/reactioncommerce/reaction/pull/3472
=> docs for CSV component

developer/community.md
- Changes 9AM PST to 7 AM PST.
=> copy: update call time

admin/faq.md, developer/developer-faqs.md
- Puts all _developer_ questions into the Dev FAQ: https://docs.reactioncommerce.com/reaction-docs/machikoyasuda-update-faqs/developer-faq
- Adds a link to the Dev FAQ in the store operator FAQ: https://docs.reactioncommerce.com/reaction-docs/machikoyasuda-update-faqs/faqs
- Adds another link to the Swag shop demo store, since that's been coming up a lot.
=> faq: better organize Developer v. Store Operator FAQ

developer/community.md
links updated w/ suggestions from @prinzdezibel's review
=> links: update community call agenda and archive links

admin/marketplace-merchant-setup.md
closes https://github.com/reactioncommerce/reaction-docs/issues/438
=> typo: fix typo

admin/marketplace-merchant-setup.md
closes #441 
from @pmn4 here: https://github.com/reactioncommerce/reaction-docs/commit/ae850a3b3b4581f5e839e5bfa02975c4e7e1dd96#commitcomment-25633608
=> docs: add instructions for Stripe Connect redirect URI

developer/git-style-guide.md
testing: https://docs.reactioncommerce.com/reaction-docs/fix-machikoyasuda-link/git-style-guide
=> fix: add link to pr review section

redoc.json
=> toc: take down CSV Download for now, because it is not part of core yet.

developer/styleguide.md
=> (docs): #463 - document new ESLint import order rules, as enforced starting 1.7

developer/contributing.md
Updates JSDoc link in Contributing Guide
=> docs: update link

developer/contributing.md
=> docs: update Issue labels

developer/core/accounts.md
This is the first time I've ever used "Edit on Github" believe it or not.
=> Correct location of accounts

admin/faq.md, developer/deploying.md, developer/deploying/platform.md, developer/developer-faqs.md
closes #484 requested by @cindyfirestone
=> copy: removes Reaction Platform links

developer/architecture/metadata.md
Added details on how to use the newly added `dom` core package used to manipulate the document meta tags.
=> Add docs for reaction dom core package.

admin/faq.md, developer/components/API.md, developer/deploying.md, developer/deploying/platform.md, developer/developer-faqs.md, developer/module-cheatsheet.md
Resolves #494 
Adds documentation for our `withMoment()` `HOC` to the module import cheatsheet, and the Reaction API docs.
=> (docs): withMoment() HOC documentation

developer/contributing.md
closes #480 #481 #486 
adds process for:
1. making a Feature Request issue https://github.com/reactioncommerce/reaction-docs/issues/486
2. community team triage process
=> docs: #481, #486 - outline code review / feature request process

developer/developer-faqs.md
Add TOOL_NODE_FLAGS for custom docker builds to avoid memory errors
=> (feat) FIx issue #426

developer/testing/acceptance-testing.md, package.json
Documentation on acceptance testing the order fulfillment workflow.
Documented based on the steps @cassytaylor and I took during our QA day.
=> docs: order fulfillment process acceptance testing docs

developer/testing/acceptance-testing.md
Fixes reference to "reaction-sample-data" and "Generic" payment method which don't exist anymore
=> Change some obsolete references

developer/community-resources.md
closes https://github.com/reactioncommerce/reaction-docs/issues/508
- adds https://github.com/artlimes/meteor-chrome-spiderable
- adds Reaction DevTools
=> docs: update community resource pg

developer/developer-faqs.md
https://docs.reactioncommerce.com/reaction-docs/fix-machikoyasuda-patch-1/developer-faq
=> fix(faq): fix homepage tutorial link

developer/contributing.md
=> docs(contributing): The Reviewer is responsible for merging the PR.

developer/packages/registry.md
closes #437 
closes #12 
test link: https://docs.reactioncommerce.com/reaction-docs/437-machikoyasuda-docs-architecture-registry/registry
=> docs(registry): update Registry with Spencer's blog post

developer/testing/release-process.md
=> docs(release process): update release process with post-release checklist

developer/architecture/schemas.md, developer/components/API.md
- Updates for switch to NPM SimpleSchema
- Clarify proper ways to extend, override, replace, and reference schemas
Closes https://github.com/reactioncommerce/reaction/issues/3494
Connected to https://github.com/reactioncommerce/reaction/pull/3331
=> docs(schemas): Updates for switch to NPM SimpleSchema

developer/architecture/i18n.md, developer/configuration.md, developer/core/import.md, developer/testing/release-process.md, developer/tutorial/plugin-fixtures-5.md, redoc.json
=> #491: Rename Import to Importer

developer/testing/release-process.md
note to self: don't edit via GitHub UI anymore! the linting errors are not as obvious.
=> chore: lint

developer/swag-shop/introduction.md, developer/swag-shop/swag-shop-collecting-requirements.md, developer/swag-shop/swag-shop-initialization.md, developer/swag-shop/swag-shop-landing-page.md, developer/swag-shop/swag-shop-pdp.md, redoc.json
This PR resolves issue #543 
https://docs.reactioncommerce.com/reaction-docs/docs-543-prinzdezibel-create-swag-shop-tutorial/swag-shop-tutorial
=> Aggregate swag shop blog posts into a developer tutorial.

developer/graphql-intro.md
Covers:
- how to start graphql via regular server
- how to authenticate
- how to make a viewer query
- how to use a mutation method
=> docs(graphql): making your first viewer query and mutation

developer/architecture/collections.md, developer/architecture/schemas.md, developer/core/event-hooks.md, developer/swag-shop/swag-shop-landing-page.md, developer/swag-shop/swag-shop-pdp.md
Updating docs to be compatible with 1.11
=> docs: use Reaction Commerce npm modules, Logger, Hooks, Schemas

redoc.json
=> chore: add graphql to toc as a tutorial

developer/getting-started.md
=> docs(links): remove broken links + remove outdated list of files/plugins

redoc.json
=> docs(toc): remove Reaction Platform from TOC

developer/installation/installation-linux.md, developer/installation/installation-osx.md, developer/installation/installation-windows.md
Add a note that Reaction is currently not compatible with Node 9
=> docs(installation): update Installation docs to note Node 8 LTS

developer/developer-faqs.md, developer/installation/development-troubleshooting.md, developer/installation/docker-development.md, developer/installation/installation-osx.md, redoc.json
Add `Developing in Docker` and `Development Troubleshooting` sections, and a few adjustments to existing installation docs
=> docs: installation updates

developer/community-showcase.md
clicking on the link leads to a 404 error
=> remove IT furniture store from showcase

developer/installation/docker-development.md
Add suggestions on how to give docker more memory if you are experiencing issues while developing.
=> add troubleshooting info for memory issues

public-docs/database-optimizations.md, public-docs/prerender.md, website/i18n/en.json, website/sidebars.json
Resolves #624  
I took @Akarshit's docs and added it to the new docs repo! thank you @Akarshit for your patience 🙏
=> Database optimizations

public-docs/community-channels.md
=> docs: remove community call link

public-docs/intro.md
=> docs: remove roadmap sidebar

README.md
=> docs: document release process

public-docs/graphql-api.md, website/i18n/en.json, website/sidebars.json
Resolves #669  
Type: **docs|chore**
The GraphQL API documentation is not easy to read, b/c it requires you to run the app first.
1. Read the docs
=> docs: add generated graphql api docs

public-docs/understanding-hydra-setup.md, website/i18n/en.json, website/sidebars.json, website/versioned_sidebars/version-2.0.0-rc.1-sidebars.json
- Add Hydra to public-docs
- Remove duplicates from both 2.0 and next sidebars
=> test on staging: fix everything

website/siteConfig.js, website/static/js/side-nav.js
Resolves #681   
Type: **feature**
- Keeps the sidebar into view https://github.com/facebook/Docusaurus/issues/823
- Works in Chrome, Firefox, but not Safari
Thank you https://github.com/facebook/Docusaurus/issues/823!
=> feat: scroll sidenav into view

public-docs/installation-reaction-platform.md, website/versioned_docs/version-2.0.0/installation-reaction-platform.md
Type: **docs**
I noticed a few typos in the new installation docs.
=> docs: installation article typos

public-docs/understanding-hydra-setup.md
Resolves #694  
Type: **docs**
=> docs: update hydra client creation docs

public-docs/how-to-create-a-payment-provider.md, website/versioned_docs/version-2.0.0/how-to-create-a-payment-provider.md, website/versioned_docs/version-2.0.0/payment.md
Type: **docs**
Updates to articles related to payment method changes in 2.0
=> docs: update payment method docs

public-docs/how-to-add-address-validation-service.md, public-docs/operator-address-validation.md, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-2.0.0/how-to-add-address-validation-service.md, website/versioned_docs/version-2.0.0/operator-address-validation.md, website/versioned_docs/version-2.0.0/tax.md, website/versioned_sidebars/version-2.0.0-sidebars.json
Type: **docs**
Add for 2.0:
- "How To: Add an Address Validation Service" developer docs
- "Address Validation" operator docs
Update the "Tax" operator docs for 2.0
=> Address validation and tax article updates

public-docs/recommended-tools.md
=> Added Altair GraphQL Client firefox addon

public-docs/how-to-write-tests-for-plugins.md, public-docs/testing-reaction.md, website/i18n/en.json, website/sidebars.json
This PR adds a doc on how to write Jest test for the plugins. 
The target audience is the plugin's author.
=> added docs for writing tests

public-docs/community-showcase.md, website/versioned_docs/version-1.14.0/community-showcase.md, website/versioned_docs/version-v1.8.0/community-showcase.md
=> docs: update spelling of Ninety Plus Wine

public-docs/shipping-admin.md
Type: **docs**
Reaction has added shipping restrictions and order surcharges. These docs guide the way to how they work.
=> docs: Shipping Restrictions and Order Surcharges

public-docs/swag-shop-05-custom-home-page.md
=> Update swag-shop-05-custom-home-page.md for new routes.js

public-docs/contributing-to-reaction.md, public-docs/dev-how-do-i.md, public-docs/graphql-developing.md, public-docs/graphql-using.md, public-docs/how-to-create-a-fulfillment-methods-plugin.md, public-docs/installation-reaction-platform.md, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-1.14.0/contributing-to-reaction.md, website/versioned_docs/version-2.0.0/dev-how-do-i.md, website/versioned_docs/version-2.0.0/graphql-developing.md, website/versioned_docs/version-2.0.0/graphql-intro.md, website/versioned_docs/version-2.0.0/graphql-using.md, website/versioned_docs/version-2.0.0/how-to-create-a-fulfillment-methods-plugin.md, website/versioned_docs/version-2.0.0/installation-reaction-platform.md, website/versioned_docs/version-v1.12.0/contributing-to-reaction.md, website/versioned_docs/version-v1.8.0/contributing-to-reaction.md, website/versioned_docs/version-v1.9.0/contributing-to-reaction.md, website/versioned_sidebars/version-2.0.0-sidebars.json
Type: **docs**
- add "Create a Fulfillment Methods Plugin" article
- corrected some GraphQL paths and auth instructions
- add some "how do I" sections
- clarify in the pull request / contributing docs that most PRs should be against `develop`
=> Various updates and fixes

public-docs/how-to-add-tax-service.md, public-docs/how-to-store-custom-order-fields.md, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-2.0.0/how-to-add-tax-service.md, website/versioned_docs/version-2.0.0/how-to-store-custom-order-fields.md, website/versioned_sidebars/version-2.0.0-sidebars.json
Type: **docs**
- Document `customFields` for tax services
- Document `customFields` for orders
These are new features in 2.0, recently merged into develop.
=> Document customFields

public-docs/swag-shop-07-graphql-server-plugin.md
Type: **docs**
Fixed grammatical error.
=> Fixed grammar

public-docs/installation-reaction-platform.md
=> docs(reaction platform): add make clone

public-docs/concepts-products.md
closes #581 
In which I attempt to translate what `<=` means into words.
=> docs(product badges): add concept docs for inventory on products

public-docs/creating-test-data.md
- explain and show how to use an iterator inside a `makeMany` inside another `makeMany`
=> docs(mocks): mocking objects within objects

public-docs/dev-how-do-i.md, website/versioned_docs/version-2.0.0/dev-how-do-i.md
Type: **docs**
Add import location for `collectionIndex`
=> docs: add collectionIndex import

public-docs/how-to-create-a-fulfillment-methods-plugin.md, public-docs/how-to-manage-app-settings.md, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-2.0.0/how-to-create-a-fulfillment-methods-plugin.md, website/versioned_docs/version-2.0.0/how-to-manage-app-settings.md, website/versioned_sidebars/version-2.0.0-sidebars.json
Type: **docs**
A new "How To: Manage App Settings" article that explains how to use the settings API for developers.
=> Document the new settings API

website/core/Footer.js
Resolves https://github.com/reactioncommerce/reaction-static/issues/243
Type: **chore**
Point footer Partner link to new `become-a-partner` page.
=> Smol PR to update Footer Link

docs/architecture/decisions/0003-tutorial-deprecation-plan.md, public-docs/installation-reaction-platform.md, public-docs/intro-glance.md, public-docs/react-testing.md, public-docs/storefront-intro.md, public-docs/swag-shop-01-what-is-the-example-storefront.md, public-docs/swag-shop-02-preparing-for-changes.md, public-docs/swag-shop-03-custom-styling.md, public-docs/understanding-hydra-setup.md, website/i18n/en.json, website/versioned_docs/version-2.0.0/installation-reaction-platform.md, website/versioned_docs/version-2.0.0/intro-glance.md, website/versioned_docs/version-2.0.0/storefront-intro.md, website/versioned_docs/version-2.0.0/swag-shop-01-what-is-the-example-storefront.md, website/versioned_docs/version-2.0.0/swag-shop-02-preparing-for-changes.md, website/versioned_docs/version-2.0.0/swag-shop-03-custom-styling.md, website/versioned_docs/version-2.0.0/understanding-hydra-setup.md
Closes https://github.com/reactioncommerce/reaction-docs/issues/828
Updated all refs to "starter kit" to "example-storefront"
=> chore: updated starterkit copy to example storefront.

website/versioned_docs/version-2.0.0/installation-reaction-platform.md
Add recommended settings for Docker and note regarding credentials for classic UI.
=> docs: add recommended settings for docker for mac, and note regarding credentials

public-docs/dashboard.md
=> docs: removes search

public-docs/dashboard.md, website/versioned_docs/version-2.0.0/dashboard.md
=> Machikoyasuda patch 1

website/sidebars.json, website/versioned_sidebars/version-2.0.0-sidebars.json
=> Hotfix sidebar

README.md
Signed-off-by: Machiko Yasuda <machiko@reactioncommerce.com>
=> docs: add build step; fix h3 vs h2

public-docs/core-plugins-stripe.md, public-docs/how-to-add-tax-service.md, public-docs/intro-glance.md, public-docs/intro.md, public-docs/storefront-checkout-page.md, public-docs/storefront-intro.md, public-docs/storefront-inventory-status-badges.md, website/versioned_docs/version-1.15.0/core-plugins-stripe.md, website/versioned_docs/version-1.15.0/how-to-client-checkout-flow.md, website/versioned_docs/version-2.0.0/core-plugins-stripe.md, website/versioned_docs/version-2.0.0/how-to-add-tax-service.md, website/versioned_docs/version-2.0.0/intro-glance.md, website/versioned_docs/version-2.0.0/intro.md, website/versioned_docs/version-2.0.0/storefront-checkout-page.md, website/versioned_docs/version-2.0.0/storefront-intro.md, website/versioned_docs/version-2.0.0/storefront-inventory-status-badges.md
Reaction Design System -> Example Storefront Component Library
=> docs: Example Storefront Component Library rename

public-docs/release-process.md
Update release notes docs to match the updated version we were keeping in notion.
=> docs: update release-process docs to match notion

public-docs/deploying.md
Configuration link was returning 404. Going to https://docs.reactioncommerce.com/docs/configuration.md instead of https://docs.reactioncommerce.com/docs/configuration
=> Fix url typo.

public-docs/installation-docker-development.md
The link was redirecting to a 404.
=> Fix the installation link

public-docs/community-resources.md
Type: **docs**
https://github.com/trojanh/reaction-wishlist
Adds plugin to add product wishlist support for logged in users.
N.A.
N.A.
N.A.
=> Add Wishlist plugin

public-docs/recommended-tools.md
Signed-off-by: Chris Potter <chris@reactioncommerce.com>
Resolves reactioncommerce/catalog-publisher#171
Type: **docs**
Kafka Helpers section for topic data visualizers
=> update docs with kafka tooling

public-docs/swag-shop-08-creating-featured-products-component.md
Signed-off-by: trojanh <rajan.tiwari@kiprosh.com>
Resolves https://github.com/reactioncommerce/reaction-docs/issues/891
Type: **refactor**
Update `Preparing for Upstream changes` tutorial to make `featuredProductsByShop` query context more clear and some minor changes.
=> Add GraphQL query link in swag-shop-08
