developer/themes/templates.md

Initially replaced it with references to Flow Router, but really there doesn't need to be anything there about routing and the Routing section covers everything you need to know.

Remove references to Iron Router

---

developer/requirements.md

Windows OpenSSL errors prevent startup block has broken link wich points to devel branch of meteor/packages/non-core/npm-node-aes-gcm, but appears only in branch `release >= 1.4.0.2 (tree/release-1.4.0.2)`

Update broken link in requirements.md

---

developer/tutorial/creating-a-theme.md

Based off of a question in Gitter, I added a line that instructs people they need to stop and restart Reaction in order to load a plugin for the first time (particularly a custom theme).

Added a note on restarting Reaction to load plugins

---

developer/installation.md

Remove the section that says you can use `meteor` CLI instead.  The plugin/styles loaders make `reaction-cli` required.

reaction-cli is required

---

developer/architecture/layout.md
developer/tutorial/plugin-layouts-3.md

Updating the tutorial after changes made in [#2023](https://github.com/reactioncommerce/reaction/pull/2023).  (which is the changing of layout priority default value and using that to allow overriding of templates).
What to review:
* The main comment is in the `plugin-layouts-3.md` file. Check if the description is sufficient.
* Is there any other part of the docs (related to layouts) that needs a similar comment to the one I've added? (so far I've found just that one file)

Update docs to reflect change to priority field default value

---

redoc.json

The "Customizing Templates" nav item was displayed twice under the Customization Guide section of the sidebar.
Reference: https://docs.reactioncommerce.com/reaction-docs/master/plugin-customizing-templates-4

Removing duplicate nav item

---

admin/dashboard.md
developer/community.md

- Changed lead to @machikoyasuda, from @sophiehe 
- Changed time from 3PM to 3:30PM so the meetings don't overlap with Components' meeting
https://docs.reactioncommerce.com/reaction-docs/machikoyasuda-patch-1/community-channels

Update Documentation project lead and time

---

developer/community.md

as per @zenweasel from https://github.com/reactioncommerce/reaction-docs/pull/209#pullrequestreview-46711877
see the changes live: https://docs.reactioncommerce.com/reaction-docs/remove-plugins/community-channels

remove Plugins project meeting

---

developer/core/payments.md

Closes https://github.com/reactioncommerce/reaction-docs/issues/207
- Use direct `docPath` from `redoc.json` instead of the `alias`
- Linked to the Creating a Payment Provider tutorial instead of the deprecated package
Test the changes live: https://docs.reactioncommerce.com/reaction-docs/207-broken-payment-urls/reaction-payments

fix Payment Method links by using docPath instead of the alias

---

developer/requirements.md

Tested and confirmed working on CentOS 7.  
To test:
```sh
docker run -it --rm centos:7 /bin/bash
yum groupinstall "Development Tools"
yum install epel-release
yum install GraphicsMagick nodejs
npm i -g reaction-cli
reaction init
cd reaction 
export METEOR_ALLOW_SUPERUSER=true
reaction
```

add build tools install instructions for CentOS

---

package.json

Update ESLint to current version to silence Bithound warning.

Update ESLint to current

---

redoc.json

sophie pointed out that above `Code of Conduct`, you can hover and click on a link to the guidelines.. but there is no link text there. i had no idea there was a 👻  link there. 
so i brought it back in `redoc.json`
test here: https://docs.reactioncommerce.com/reaction-docs/community-url-in-toc/intro

add missing label for Community Guidelines so it's not a ghost link

---

developer/community.md

- Consolidate the separate project topic calls into 2 monthly calls, on the 1st and 3rd Wednesdays. (Reaction Actions are usually the last week of the month).
- Adds a public Google Doc agenda to archive conversations from the calls: https://docs.google.com/document/d/1PwenrammgQJpQfFoUUJZ96i_JJYCM_4glAjB1_ZzgwA/edit?usp=sharing

Update community call schedule

---

developer/tutorial/plugin-customizing-templates-4.md

On the section **client/index.js** the import points to `./components` but it should say `./templates` in this context.

Fix wrong import in plugin-customizing-templates-4.md

---

developer/tutorial/plugin-layouts-3.md

In Reaction 1.5 the imports can point to the reaction package instead of using an absolute path to the plugin.
In this case replace `import { registerComponent } from "/imports/plugins/core/layout/lib/components";` with `import { registerComponent } from "@reactioncommerce/reaction-components";`

Fix outdated Import

---

developer/testing/release-process.md

Adds two steps:
- Delete the release branch after it's all over
- `Merge` into master, not `Squash and Merge`

Remove squashing from release process

---

developer/deploying/platform.md

To get all application logs since your app's last startup:
```sh
reaction logs --app <appname>
reaction logs -a <appname>
```
For the explanation about why you can't currently tail logs, I'll take the comment from https://github.com/reactioncommerce/launchdock/pull/114#issuecomment-345888875
> Well, I should probably have stated the caveat that this is the MVP for the logs API.  I just wanted to give people a way to debug their deployments as soon as possible.  By default, you get _all_ of the logs since the app last started.  That can be adjusted by line count or "since" time, but I haven't enabled those flags in the CLI yet.  
>
> Tailing _will_ be possible, but it's significantly more complicated for a few reasons.  The main one being because users can potentially have multiple …

document ‘reaction logs’ command

---

developer/tutorial/creating-a-payment-provider-plugin.md

There was still another thing not up-to-date in the tutorial.
I've read through it and hope, everything's ok now, but I can't guarantee, because I didn't take the time to play it through , step-by-step, on my local computer. Please let me know if I'm supposed to do so.

Fix wrong path and blaze template references in payment provider tutorial.

---

developer/styleguide.md

Fix the listing of import order to have each item on new line instead of all on the same line.
This improves readability.

Update style for import order list

---

developer/git-style-guide.md
redoc.json

closes https://github.com/reactioncommerce/reaction-docs/issues/414
re-submitted from https://github.com/reactioncommerce/reaction-docs/pull/345, which i messed up from some hasty rebasing
document Git commit message, branch naming style
https://docs.reactioncommerce.com/reaction-docs/docs-414-machikoyasuda-git-guide/git-style-guide

#414: add git guide

---

index.md

- Removes link to https://styleguide.reactioncommerce.com
- Adds link to https://docs.reactioncommerce.com/reaction-docs/master/installation and https://docs.reactioncommerce.com/reaction-docs/master/tutorial
- Updates blog posts with Spencer and Michael's latest posts
https://docs.reactioncommerce.com/reaction-docs/machikoyasuda-remove-styleguide/intro

design: removes Style Guide, adds Tutorials section

---

redoc.json

closes #328 and #110
- adds new sections: `Plugin Tutorial`,  `Getting started`, `Contributing`, `Guides`
- WIP: add new Start page, a la https://docs.djangoproject.com/en/2.0/
- experience it IRL: https://docs.reactioncommerce.com/reaction-docs/328-machikoyasuda-toc-best-practices/intro
before:
after:

toc: divide up into more categories (#328)

---

developer/git-style-guide.md

At the bottom of the [Git style guide](https://docs.reactioncommerce.com/reaction-docs/master/git-style-guide) page the link to the **code review process guide** was  returning `404`. The URL path was `/developer/code-review.md` I've updated it to be `/developer/code-reviews.md`. I figured it was better to update the URL path rather than changing the `code-reviews.md` file name.

fix: Updated bad link path on git style guide page

---

redoc.json

Clicking on the CLI docs link on [1] doesn't load any content.
This commit updates redoc.json in an attempt to resolve this.
[1] https://docs.reactioncommerce.com/reaction-docs/master/installation-linux

Add Reaction CLI link to redoc.json

---

developer/core/email.md
developer/deploying.md
developer/getting-started.md
developer/tutorial/introduction.md

The link /admin/email.md doesn't exist, so we update links to point to
/admin/dashboard/email-admin.md.
The link configuration.md doesn't exist, so we point to
/developer/configuration.md.
The link /developer/tutorial/customization.md was renamed to
/developer/tutorial/introduction.md in a6769b8, so we update the
reference here.
The link /developer/tutorial/creating-a-plugin.md doesn't exist, so we
point to /developer/tutorial/plugin-creating-2.md.

General doc cleanup

---

.circleci/config.yml
developer/tutorial/introduction.md
package.json

closes #468 
- Configure CircleCI to run `npm run lint`: I just copied @zenweasel in https://github.com/reactioncommerce/reaction-component-library/blob/master/.circleci/config.yml
- Configure `remark-lint` to Error instead of Warn
- I added the `-frail` flag to `npm run lint`
- I purposefully made a linting error
- I pushed up the error
- I observed CircleCI fail:
- Then... I fixed the error and pushed it back up so this PR can still pass 💯

(chore): #468 add npm install to circle ci

---

developer/jsdoc-style-guide.md
redoc.json

closes #281 
Based off of https://github.com/reactioncommerce/reaction-jsdoc/blob/master/README.md
This guide is a very explicit guide on how I have documented methods, modules and more to produce http://api.docs.reactioncommerce.com/ The parts about documenting methods is fairly generic, but gets more opinionated around Schemas, etc. I suspect there will be changes in how we organize modules in future version of Reaction, which may need to be reflected differently in docs in the future. I think we should get this up now and update it moving forward.

(docs): #281 add guide on how to write JSDoc and how to run it locally

---

developer/react-best-practices.md

Fix typo error in React best practices

Fix typo error in React best practices

---

developer/contributing.md

Adds a pull request template and details to help improve the quality of PR's into core Reaction.

(doc): add pull request template

---

developer/architecture/images.md
developer/installation/installation-linux.md
developer/installation/installation-osx.md
developer/installation/installation-windows.md

- Removed all install instructions for ImageMagick/GraphicsMagick from install docs.
- Replaced CFS GraphicsMagick link with link to Sharp in image docs.

Docs 493 nnnnat remove imagemagick

---

developer/error-handling-guide.md
redoc.json

closes #513
I added information from https://github.com/reactioncommerce/reaction/pull/3195 for
```access-denied
not-implemented
invalid-parameter
not-configured
server-error
not-found
``` 
with some background information on `Meteor.Error()` from the Meteor guide.
Test: https://docs.reactioncommerce.com/reaction-docs/513-machikoyasuda-error-messaging/error-handling-guide

docs(errors): add Error messaging page and section

---

developer/themes/helpers.md
redoc.json

closes #502 
- updated link to https://github.com/reactioncommerce/reaction/tree/v1.8.0/client/modules/core/helpers
- added link to http://api.docs.reactioncommerce.com/Helpers.html
- moves Helpers link under Architecture, not Tutorials/Guides.

fix(link): fix Helpers module link and add API Docs Helpers link.

---

developer/configuration.md

Updates docs related to `METEOR_SETTINGS` / `settings.json` deprecation.
It seems we already explain adding the data that was in `settings.json` to the `ENV` in the [`REACTION_` section](https://docs.reactioncommerce.com/reaction-docs/master/configuration#reaction), so I don't believe any _new_ documentation is needed.
See https://github.com/reactioncommerce/reaction/pull/3951

docs: remove references to using settings.json to load METEOR_SETTINGS

---

developer/configuration.md
developer/deploying/docker.md
developer/testing/release-process.md

Docs reflecting Docker Compose file changes in Reaction release-1.9.0
Adds the following lines to deploy.md file.
---------------
You can also use Docker Compose to run Reaction and Mongo in separate connected Docker containers.
We've included a demo [docker-compose file](https://github.com/reactioncommerce/reaction/blob/master/docker-compose-demo.yml) in the repository. In it's current basic form, it is meant for quickly running a demo of your production build. It can also serve as starting point for your production docker-compose setup.
If you have a custom Docker image of your Reaction app, you can modify the `docker-compose-demo.yml` file to point to use it by changing the `image` name of the `reaction` service.
```yml
services:
reaction:
image: custom-image
depends_on:
- mongo
.... …
```

Add steps to run App Build with Docker Compose

---

developer/revisions.md

Add docs describing how changes are published from revisions to products and then finally to the catalog.

docs: add catalog and revision publishing

---

developer/community-resources.md

I've tested this plugin and it's simple but it works after they merged my PR to update to the current version of simple-schema, etc.
https://github.com/DeligenceTechnologies/Subscription-Recurring-payments-in-Reaction-Commerce-using-Braintree-Payments-Gateway/pull/1#issuecomment-377469767

Add Braintree Subscription plugin to Community Resources

---

developer/testing/creating-test-data.md

With the new  [data-factory](https://github.com/reactioncommerce/data-factory) package and PRs [4266](https://github.com/reactioncommerce/reaction/pull/4266) + [4276](https://github.com/reactioncommerce/reaction/pull/4276) creating mock data for jest testing has changed. I've updated the [Creating Test Data](https://docs.reactioncommerce.com/reaction-docs/master/creating-test-data) section with examples of how to use the new mock data `Factory`.

docs: updated testing mock data section

---

redoc.json

Fix the path to https://github.com/reactioncommerce/reaction-docs/blob/master/developer/core/import.md

hotfix: reaction importer url is breaking

---

developer/architecture/prerender.md
developer/contributing.md
developer/installation/installation-linux.md
developer/installation/installation-osx.md
developer/installation/installation-windows.md
redoc.json

If https://github.com/reactioncommerce/reaction/pull/4331 gets merged, then the docs on prerender have to be updated as suggested in this PR.

(fix) Update prerender guide

---

public-docs/contributing-to-reaction.md

Resolves: Unreported issue
Type: **docs**
Descriptions for the `npm run lint` and `reaction test` commands were backwards.
Switched descriptions
None
1. Visit the main "Contributing Guide" page -> "Pass all tests"
2. Confirm the description for `npm run lint` reads "Pass linter code review and follow Reaction style guidelines".
3. Confirm the description for `reaction test` reads "Pass current continuous integration tests"

(fix): correct text for lint and test commands

---

public-docs/release-process.md

Adds new step to release process to update the [sample data](https://github.com/reactioncommerce/reaction-catalog-sample-data/) repo with migrations. This step was added based on this suggestion https://github.com/reactioncommerce/reaction-catalog-sample-data/issues/1
Also changes the release process to better match our current process.

fix: update release process

---

public-docs/plugin-creating-2.md

Impact: **major**  
Type: **docs**
Import path for the `registerPackage` method was outdated in the plugin tutorial.
Update the import path to `/imports/plugins/core/core/server/Reaction`.

Update registerPackage import path in plugin tutorial

---

public-docs/permissions.md
public-docs/reaction-orders.md
public-docs/reaction-payments.md
public-docs/reaction-user-accounts.md

Resolves #658   
Type: **docs|chore**
Update docs for 1.16 - use `Reaction.getUserId()` instead of `Meteor.userId()`

docs(1.16): use Reaction.getUserId() instead of Meteor.userId()

---

website/core/Footer.js
website/siteConfig.js

Resolves reactioncommerce/reaction-static#131
Type: **chore**
The Get in Touch button needs to be pointed to the Act On form.
Updates the link to point to the right page.

update get in touch buttons to point to act on form

---

website/versioned_docs/version-2.0.0-rc.1/understanding-hydra-setup.md
website/versioned_sidebars/version-2.0.0-rc.1-sidebars.json

Resolves reactioncommerce/reaction-hydra#6
Type: **docs**
- Adds docs on how Ory Hydra is used as part of Reaction platform services
- Explains how a client configuration is added for the storefront
- Explains how the Identity Provider features work
- Adds links to Hydra Production guides

Add Hydra dev docs

---

public-docs/core-plugins-sitemap-generator.md
website/i18n/en.json
website/sidebars.json

Resolves #693 
Type: **feature**
This PR adds documentation for the sitemap generator plugin under the "Core Plugins" section.
None
1. Confirm "Sitemap Generator Plugin (Meteor)" Appears under "Core Plugins" in the sidebar
2. Read through and confirm docs are accurate

feat: docs for sitemap generator plugin

---

public-docs/dev-how-do-i.md
website/versioned_docs/version-2.0.0/dev-how-do-i.md

When I recently added the "how do I" article, I neglected to add content to one of the headings

docs: add missing "how do I" content

---

public-docs/how-to-extend-graphql-with-remote-schema.md
website/i18n/en.json
website/sidebars.json

Type: **docs**
This documentation goes with [reaction pull 4870](https://github.com/reactioncommerce/reaction/pull/4870), and describes how a plugin can stitch a remote graphql service into the reaction graphql API. The provided sample files should be a fully-working plugin that developers can deploy and see working locally.
That reaction PR is very likely to see significant churn before it finally merges, so keep that in mind, but starting this PR to show documentation efforts so far.

How to delegate to remote graphql

---

website/versioned_docs/version-2.0.0/how-to-add-tax-service.md
website/versioned_docs/version-2.0.0/tax.md

Resolves: N/A 
Type: **docs**
Based on the work in reactioncommerce/reaction#4871, this adds a few lines about the new shop tax setting.
Note: I updated the version-2.0.0 files. (Is this the time to update the related public-docs files too?)

docs: Include description about fallback tax service

---

public-docs/installation-reaction-platform.md

Resolves #731 
Impact: **major**  
Type: **docs**
Developing Reaction Commerce in a Windows environment has been difficult. Because the development environment is containerized, in theory development in Windows should be straightforward. In practice, there has been difficulty developing in Windows. As we are unable to support development in Windows, we’re updating our installation docs to show that.
We’d like to be able to support development in Windows and plan to revisit the policy when we can spend time troubleshooting the issues that are found in the Windows environment. 
PRs to address issues related to development in the Windows environment are welcomed!
Adjust Windows support policy in installation docs. 
n/a
1. Check that the installation docs reflect our new support policy on …

fix: add stance on Windows development support

---

public-docs/graphql-create-query.md

Type: **docs**
Adding a note related to GraphQL queries when query returns more than one document, and we need to use a `Connection` to get `edges->node`.

docs: update GraphQL query docs

---

public-docs/creating-test-data.md

Code example should be `Tag` not `Tags`.

docs: Tag, not Tags.

---

public-docs/understanding-hydra-setup.md

Type: **bugfix**
This link was incorrect and was getting rendered to localhost:4000.
Use just filename without leading "./".
- Reproduced locally and confirmed this change fixes it.

fix: Fix link between hydra and replaceComponent

---

public-docs/testing-debugging-server-code.md

closes #746 
Document the `--service-ports` trick, and the new inspect options, as of RC 9.

docs(inspect): add new inspect scripts

---

public-docs/writing-jest-integration-tests.md

- explain how to require new graphql queries, mutations, resolvers and schemas into `TestApp` (via `devserver`)
- show example code of how to add an owner admin user to integration test

docs(integration testing): add instructions to import new queries

---

public-docs/reaction-orders.md
public-docs/reaction-shops.md

Add Meteor method removed, note for `orders/addOrderEmail` and `shop/getCurrencyRates`.

docs(addOrderEmail): add method removed note

---

public-docs/blocks-api.md
website/versioned_docs/version-2.0.0/blocks-api.md
website/versioned_sidebars/version-2.0.0-sidebars.json

Type: **docs**
- There are some inconsistencies in the docs and the implementation in reaction.
- The block docs are only available if you explicitly choose `master` as a version
- Fix typos
- Copy docs to 2.0.0
none
1. Ensure the docs are more accurate
2. Ensure the docs show up for version `2.0.0` / `next` as well as `master`

fix: block api typos, copy to version 2.0.0

---

website/versioned_sidebars/version-2.0.0-sidebars.json

Resolves #804   
Type: **docs|chore**
Removes SMS from the sidebar to remove deprecated functionality

Removes sms from sidebar in version-2.0.0 to coincide with master branch

---

public-docs/graphql-developing.md
public-docs/graphql-intro.md
public-docs/graphql-using.md
public-docs/installation-reaction-platform.md
public-docs/storefront-apollo-client.md
website/versioned_docs/version-2.0.0/graphql-developing.md
website/versioned_docs/version-2.0.0/graphql-intro.md
website/versioned_docs/version-2.0.0/graphql-using.md
website/versioned_docs/version-2.0.0/installation-reaction-platform.md
website/versioned_docs/version-2.0.0/storefront-apollo-client.md

As preparation for the 2.0 release of Reaction, the GraphQL endpoint has been renamed to `graphql-beta` to indicate increased stability.

rename the GraphQL endpoint to graphql-beta

---

public-docs/reaction-cli.md

Issue: Resolves unreported issue
Type: **docs**
The [Reaction CLI](https://docs.reactioncommerce.com/docs/next/reaction-cli) doc lists various commands but it doesn't mention installing it. I found this information in the [Reaction Platform](https://docs.reactioncommerce.com/docs/next/deploying-on-reaction-platform) doc and I think it would be useful to have it also here. I also found a typo in the second doc, which I'm fixing in the same PR. 
Added a sentence and a code snippet telling people how to install the CLI. Also, fixed a typo in another doc. 
None.
1. Check that the new sentence + code snippet has been added at the [Reaction CLI](https://docs.reactioncommerce.com/docs/next/reaction-cli) doc
2. Check that the "Beforey" typo has been removed from [Reaction …

Add note at the Reaction CLI doc on how to install the CLI

---

public-docs/installation-reaction-platform.md
website/versioned_docs/version-2.0.0/installation-reaction-platform.md

Resolves #838 
Impact: **major**  
Type: **docs**
These docs:
- [Install with Reaction Platform](https://docs.reactioncommerce.com/docs/next/installation-reaction-platform)
- [Install with Reaction Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform)
need instructions on how to upgrade a) from 1.x, or b) from an older 2.0 release candidate
Also we must add a section on develop vs master branches and a warning that reaction CLI has been deprecated.
None.
Check the following paragraphs:
- http://localhost:4242/docs/installation-reaction-platform#upgrading-from-1x
- http://localhost:4242/docs/installation-reaction-platform#upgrading-from-an-older-20-release-candidate
- http://localhost:4242/docs/installation-reaction-platform#repository-branches
- …

Add Upgrade to 2.0 Instructions

---

website/sidebars.json
website/versioned_sidebars/version-2.0.0-sidebars.json

Signed-off-by: Christopher Shepherd <christopher@reactioncommerce.com>
Resolves #847 
Type: **docs**
Removes sidebar links to deprecated Meteor components; Also removes v2.0.0 versioned documentation for PrimaryAppBar (ie versioned_docs/version-2.0.0/components-primary-app-bar.md)

Remove Meteor component topics from sidebars for v2.0.0 and 'next' as indicated

---

public-docs/reaction-cli.md
website/versioned_docs/version-2.0.0/reaction-cli.md

Resolves -
Type: **docs**
The output of `grep version package.json` is:
```
"version": "2.0.0",
"last 2 versions"
```
which is not very clean. We want something cleaner.
I added a `version` script at [package.json of reaction repo](https://github.com/reactioncommerce/reaction/blob/develop/package.json#L222) that echoes the value of `$npm_package_version`. 
Run it with: `npm run version --silent`.
The output is `2.0.0-rc.10`.
This PR is updating the docs to use the same script.
Right now the script exists only in `develop`, not in `master`, so maybe we should hold off merging this PR?
1. Go to [Reaction CLI](https://docs.reactioncommerce.com/docs/reaction-cli#check-version) and verify that the script displayed is `npm run version --silent`.
2. Run `npm run version …

(docs) update how to get reaction version

---

public-docs/graphql-create-query.md
public-docs/graphql-developing.md
public-docs/how-to-share-code-between-plugins.md
public-docs/running-jest-integration-tests.md
public-docs/running-jest-unit-tests.md
public-docs/writing-jest-integration-tests.md
website/i18n/en.json
website/sidebars.json
website/versioned_docs/version-1.14.0/graphql-developing.md
website/versioned_docs/version-1.14.0/writing-jest-integration-tests.md
website/versioned_docs/version-2.0.0/graphql-create-query.md
website/versioned_docs/version-2.0.0/graphql-developing.md
website/versioned_docs/version-2.0.0/how-to-share-code-between-plugins.md
website/versioned_docs/version-v1.12.0/running-jest-integration-tests.md
website/versioned_docs/version-v1.12.0/running-jest-unit-tests.md
website/versioned_sidebars/version-2.0.0-sidebars.json

Type: **docs**
- new "How to share code between API plugins" article
- add naming rules to the GraphQL query article
- some small fixes to Jest testing articles

New sharing code article and some fixes

---

public-docs/git-style-guide.md

Resolves #756   
Type: **docs**
Reaction requires all OSS contributors to agree to the [Developer Certificate of Origin (DCO)](https://developercertificate.org/) when contributing code back to a project. This info is scattered across several repos but not in the centralized Reaction documentation.  
I've included our DCO copy to the Git Styleguide page.
> We use the [Developer Certificate of Origin (DCO)](https://developercertificate.org/) in lieu of a Contributor License Agreement for all contributions to Reaction Commerce open source projects. We request that contributors agree to the terms of the DCO and indicate that agreement by signing all commits made to Reaction Commerce projects by adding a line with your name and email address to every Git commit message …

(docs): added DCO copy to git style guide docs
